# Generated by Django 4.0.6 on 2022-07-19 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('alive', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=50)),
                ('Birthdate', models.DateField()),
                ('country', models.CharField(choices=[('INDIA', 'India'), ('RUSSIA', 'Russia'), ('ISRAIL', 'Israil'), ('ICELAND', 'Iceland'), ('AUSTRALIA', 'Australia')], default='INDIA', max_length=10)),
            ],
        ),
    ]
