# Generated by Django 4.0.6 on 2022-07-25 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_patient_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='myapp.hospital'),
        ),
    ]
