# Generated by Django 4.0.6 on 2022-08-08 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0005_remove_patient_hospital_doctor_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='myapp.hospital'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='country',
            field=models.CharField(choices=[('INDIA', 'India'), ('RUSSIA', 'Russia'), ('ISRAIL', 'Israil'), ('ICELAND', 'Iceland'), ('AUSTRALIA', 'Australia'), ('JAPAN', 'Japan')], default='INDIA', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to='myapp.doctor'),
        ),
    ]
