# Generated by Django 4.0.6 on 2022-08-17 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_hospital_h_rating_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='myapp.hospital'),
        ),
    ]
