# Generated by Django 4.0.6 on 2022-08-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_review_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='h_rcount',
            field=models.IntegerField(default=0),
        ),
    ]
