# Generated by Django 4.0.6 on 2022-08-24 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0009_hospital_h_rcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='r_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='review_creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
